---

- name: Install packages via pip
  become: true
  pip: name="{{ item.name }}" version="{{ item.version }}"
  with_items: "{{ uwsgi_pip_dependencies | default({}) }}"
  when: uwsgi_pip_dependencies is defined
