---

- name: copy templates uwsgi
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items: "{{ _uwsgi.templates  | default({}) }}"
  when: _uwsgi.templates is defined
